<a href="https://colab.research.google.com/github/riturajtigga12-netizen/ybi-foundation-internship-project/blob/main/Admission_chances.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

admission = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Admission%20Chance.csv')

admission.head()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [15]:
admission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No          400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4    SOP               400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [16]:
admission.describe()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [17]:
admission.columns

Index(['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [18]:
y = admission['Chance of Admit ']

In [19]:
X = admission.drop(['Serial No','Chance of Admit '],axis=1)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [22]:
print("First 5 records:")
print(admission.head())

First 5 records:
   Serial No  GRE Score  TOEFL Score  University Rating   SOP  LOR   CGPA  \
0          1        337          118                  4   4.5   4.5  9.65
1          2        324          107                  4   4.0   4.5  8.87
2          3        316          104                  3   3.0   3.5  8.00
3          4        322          110                  3   3.5   2.5  8.67
4          5        314          103                  2   2.0   3.0  8.21

   Research  Chance of Admit
0         1              0.92
1         1              0.76
2         1              0.72
3         1              0.80
4         0              0.65

In [23]:


print("\nDataset shape:")
print(admission.shape)

Dataset shape:
(400, 9)

In [24]:


print("\nDataset information:")
print(admission.info())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No          400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4    SOP               400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB
None

In [25]:


print("\nStatistical summary:")
print(admission.describe())

Statistical summary:
        Serial No   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000
mean   200.500000  316.807500   107.410000           3.087500    3.400000
std    115.614301   11.473646     6.069514           1.143728    1.006869
min      1.000000  290.000000    92.000000           1.000000    1.000000
25%    100.750000  308.000000   103.000000           2.000000    2.500000
50%    200.500000  317.000000   107.000000           3.000000    3.500000
75%    300.250000  325.000000   112.000000           4.000000    4.000000
max    400.000000  340.000000   120.000000           5.000000    5.000000

             LOR         CGPA    Research  Chance of Admit
count  400.000000  400.000000  400.000000        400.000000
mean     3.452500    8.598925    0.547500          0.724350
std      0.898478    0.596317    0.498362          0.142609
min      1.000000    6.800000    0.000000          0.340000
25%      3.000000    8.170000    0.000000          0.640000
50%      3.500000    8.610000    1.000000          0.730000
75%      4.000000    9.062500    1.000000          0.830000
max      5.000000    9.920000    1.000000          0.970000